### ISSUE TITLE
[Bug] No sync branch

### ISSUE THREAD

**Issue by mariusvniekerk** [temporalio/edu-101-python-code#21]
### What are you really trying to do?

The training [document](https://temporal.talentlms.com/unit/view/id:2624) contains the phrase

> The remainder of this course will demonstrate asynchronous Activities. If you would like to complete Exercise 3 using Synchronous Activities, you can switch branches in the edu-101-python-code repository to the [sync branch](https://github.com/temporalio/edu-101-python-code/tree/sync).

This branch does not exist.

**Comment by MasonEgger** [comment]
@mariusvniekerk This branch has been restored. You should see it now.
